apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: codegem-0514
  janus-idp.io/tekton: codegem-0514
  backstage.io/kubernetes-id: codegem-0514
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: codegem-0514
resources:
- deployment.yaml
- route.yaml
- service.yaml
