apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: codegem-0514
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: codegem-0514 
  name: codegem-0514
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: codegem-0514 
